name: Canadian National - Record & Transcribe

on:
  workflow_dispatch:
    inputs:
      minutes:
        description: "Recording length (minutes)"
        required: true
        default: "30"
        type: string
      model:
        description: "Whisper model"
        required: true
        default: "small"
        type: string
  # CN at 10:00 AM ET on Sept 11, 2025 = 14:00 UTC
  schedule:
    - cron: "0 14 11 9 *"

jobs:
  call:
    uses: ./.github/workflows/record_transcribe_reusable.yml
    with:
      url: "https://event.webcasts.com/starthere.jsp?ei=1732242&tp_key=6ee27846a6&tp_special=8"
      minutes: ${{ inputs.minutes }}
      model:   ${{ inputs.model }}
    secrets:
      FIRST:   ${{ secrets.CN_FIRST }}
      LAST:    ${{ secrets.CN_LAST }}
      COMPANY: ${{ secrets.CN_COMPANY }}
      EMAIL:   ${{ secrets.CN_EMAIL }}
