name: Canadian National - Record & Transcribe

on:
  workflow_dispatch:
    inputs:
      minutes:
        description: "Recording length (minutes)"
        required: true
        default: "35"
        type: string
      model:
        description: "Whisper model"
        required: true
        default: "small"
        type: string
      probe_seconds:
        description: "Short test duration (seconds). 0 = full run"
        required: true
        default: "0"
        type: string
  # CN scheduled 5 minutes early: 9:55 AM ET on Sept 11, 2025 = 13:55 UTC
  schedule:
    - cron: "55 13 11 9 *"

jobs:
  call:
    uses: ./.github/workflows/record_transcribe_reusable.yml
    with:
      url: "https://event.webcasts.com/starthere.jsp?ei=1732242&tp_key=6ee27846a6&tp_special=8"
      minutes: ${{ inputs.minutes }}
      model:   ${{ inputs.model }}
      probe_seconds: ${{ inputs.probe_seconds }}
      diarize: true
      max_speakers: "0"
    secrets:
      FIRST:         ${{ secrets.CN_FIRST }}
      LAST:          ${{ secrets.CN_LAST }}
      COMPANY:       ${{ secrets.CN_COMPANY }}
      EMAIL:         ${{ secrets.CN_EMAIL }}
      HF_TOKEN:      ${{ secrets.HF_TOKEN }}
      SMTP_SERVER:   ${{ secrets.SMTP_SERVER }}
      SMTP_PORT:     ${{ secrets.SMTP_PORT }}
      SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      MAIL_FROM:     ${{ secrets.MAIL_FROM }}
      MAIL_TO:       ${{ secrets.MAIL_TO }}
