name: Capture Manifest with Playwright

on:
  workflow_dispatch:

jobs:
  capture:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: transcripts  # set working dir to the repo folder

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Capture manifest
        env:
          OUT_DIR: out
          PAGE_URL: https://event.webcasts.com/starthere.jsp?ei=1732689&tp_key=88708506b9&tp_special=8
        run: |
          set -euo pipefail
          mkdir -p "$OUT_DIR"
          python scripts/capture_manifest.py --url "$PAGE_URL" --out "$OUT_DIR" --wait 15 --debug
          echo "Captured files in $OUT_DIR:"
          ls -la "$OUT_DIR"