name: Press Release Tracker (Yahoo Email)

on:
  # Manual trigger with inputs
  workflow_dispatch:
    inputs:
      lookback_hours:
        description: "Lookback window (hours)"
        required: true
        default: "24"
        type: string
      send_always:
        description: "Email even if 0 items? (true/false)"
        required: true
        default: "true"
        type: string
  # Scheduled runs (Mon–Fri): 08:15 & 16:20 ET (EDT=UTC-4)
  schedule:
    - cron: "15 12 * * 1-5"   # 08:15 ET
    - cron: "20 20 * * 1-5"   # 16:20 ET

permissions:
  contents: write

concurrency:
  group: press-release-tracker
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"
      OUTPUT_DIR: "outputs"
      MAIL_FROM_NAME: "Press Release Tracker"

      # From manual inputs (with defaults above)
      LOOKBACK_HOURS: ${{ inputs.lookback_hours }}
      SEND_ALWAYS:    ${{ inputs.send_always }}

      # === Yahoo email secrets (exact names you use) ===
      YAHOO_EMAIL:        ${{ secrets.YAHOO_EMAIL }}
      YAHOO_APP_PASSWORD: ${{ secrets.YAHOO_APP_PASSWORD }}
      TO_EMAIL:           ${{ secrets.TO_EMAIL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser python-dateutil

      - name: Run tracker (collect + email)
        run: python scripts/press_release_tracker.py

      - name: Commit outputs (if changed)
        run: |
          if [[ -n "$(git status --porcelain outputs)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add outputs
            git commit -m "Press Release Tracker: $(date -u +'%Y-%m-%d %H:%M:%S') UTC"
            git push
          else
            echo "No changes to commit."
          fi