name: Press Release Tracker (Yahoo Email)

on:
  # Manual trigger with inputs
  workflow_dispatch:
    inputs:
      lookback_hours:
        description: "Lookback window (hours)"
        required: true
        default: "24"
        type: string
      send_always:
        description: "Email even if 0 items? (true/false)"
        required: true
        default: "true"
        type: string
  # Scheduled runs (Mon–Fri): 08:15 & 16:20 ET (EDT = UTC-4)
  schedule:
    - cron: "15 12 * * 1-5"   # 08:15 ET
    - cron: "20 20 * * 1-5"   # 16:20 ET

permissions:
  contents: write

concurrency:
  group: press-release-tracker
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      OUTPUT_DIR: outputs
      MAIL_FROM_NAME: Press Release Tracker
      # Use inputs for manual runs; fall back to defaults for schedules
      LOOKBACK_HOURS: ${{ github.event_name == 'workflow_dispatch' && inputs.lookback_hours || '24' }}
      SEND_ALWAYS:   ${{ github.event_name == 'workflow_dispatch' && inputs.send_always   || 'true' }}
      # Secrets
      YAHOO_EMAIL:        ${{ secrets.YAHOO_EMAIL }}
      YAHOO_APP_PASSWORD: ${{ secrets.YAHOO_APP_PASSWORD }}
      TO_EMAIL:           ${{ secrets.TO_EMAIL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (if any)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Verify script exists
        run: |
          echo "Repo root: $(pwd)"
          ls -la .github || true
          test -f .github/press_release_tracker.py || (echo "ERROR: .github/press_release_tracker.py not found"; exit 1)

      - name: Run press release tracker
        run: |
          mkdir -p "$OUTPUT_DIR"
          python .github/press_release_tracker.py

      - name: Upload outputs (optional)
        uses: actions/upload-artifact@v4
        with:
          name: press-release-tracker
          path: outputs/**
          if-no-files-found: ignore
          retention-days: 14