name: Schneider National - Record & Transcribe

on:
  workflow_dispatch:
    inputs:
      minutes:
        description: "Recording length (minutes)"
        required: true
        default: "43"
        type: string
      model:
        description: "Whisper model"
        required: true
        default: "small"
        type: string
      probe_seconds:
        description: "Short test duration (seconds). 0 = full run"
        required: true
        default: "0"
        type: string
  # Schneider scheduled 5 minutes early: 11:35 AM ET on Sept 11, 2025 = 15:40 UTC
  schedule:
    - cron: "35 15 11 9 *"

jobs:
  call:
    uses: ./.github/workflows/record_transcribe_reusable.yml
    with:
      url: "https://event.webcasts.com/starthere.jsp?ei=1686422&tp_key=196fd37198&tp_special=8"
      minutes: ${{ inputs.minutes }}
      model:   ${{ inputs.model }}
      probe_seconds: ${{ inputs.probe_seconds }}
      diarize: true
      max_speakers: "0"
    secrets:
      FIRST:         ${{ secrets.SCHNEIDER_FIRST }}
      LAST:          ${{ secrets.SCHNEIDER_LAST }}
      COMPANY:       ${{ secrets.SCHNEIDER_COMPANY }}
      EMAIL:         ${{ secrets.SCHNEIDER_EMAIL }}
      HF_TOKEN:      ${{ secrets.HF_TOKEN }}
      # Yahoo email secrets
      YAHOO_EMAIL:        ${{ secrets.YAHOO_EMAIL }}
      YAHOO_APP_PASSWORD: ${{ secrets.YAHOO_APP_PASSWORD }}
      TO_EMAIL:           ${{ secrets.TO_EMAIL }}
