name: Werner Enterprises - Record & Transcribe

on:
  workflow_dispatch:
    inputs:
      minutes:
        description: "Recording length (minutes)"
        required: true
        default: "30"
        type: string
      model:
        description: "Whisper model"
        required: true
        default: "small"
        type: string
  # 7:50 PM ET on Sept 10, 2025 = 23:50 UTC
  schedule:
    - cron: "50 23 10 9 *"

jobs:
  call:
    uses: ./.github/workflows/record_transcribe_reusable.yml
    with:
      url: "https://event.webcasts.com/starthere.jsp?ei=1732689&tp_key=88708506b9&tp_special=8"
      minutes: ${{ inputs.minutes }}
      model:   ${{ inputs.model }}
    secrets:
      FIRST:   ${{ secrets.WERNER_FIRST }}
      LAST:    ${{ secrets.WERNER_LAST }}
      COMPANY: ${{ secrets.WERNER_COMPANY }}
      EMAIL:   ${{ secrets.WERNER_EMAIL }}
